# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: amirmustefa
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: weather-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: server

provider:
  name: aws
  runtime: nodejs20.x

functions:
  getEvent:
    handler: handler.getEvent
    events:
      - httpApi:
          path: /
          method: get
  changeDay:
    handler: handler.changeDay
    events:
      - httpApi:
          path: /change-day
          method: post
